# Generated by Django 5.0.2 on 2024-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0017_superadmin_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='busoperator',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
