# Generated by Django 5.0.1 on 2024-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0018_alter_buses_image_alter_busoperator_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
