# Generated by Django 5.0.1 on 2024-03-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0019_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
    ]
